server.port=8090
spring.application.name = Appointment Reminder Project
server.servlet.context-path=/reminder

#MS Sql
#db1.datasource.url= jdbc:sqlserver://SSH-DEV-SQL-001:1445;databaseName=appointment_remainder;authenticationScheme=NTLM;integratedSecurity=true;user=s-ars;password=P@ssw0rd987
#db1.datasource.url= jdbc:sqlserver://localhost;databaseName=appointment_remainder;user=sa;password=admin
db1.datasource.url= jdbc:sqlserver://localhost:1433;databaseName=appointment_remainder
#db1.datasource.url=jdbc:mysql://localhost:3306/appointment_remainder
db1.datasource.username=saa
#db1.datasource.password=admin
#db1.datasource.password=alibaba@123A
db1.datasource.password=Cognicx@123
#db1.datasource.password=ImperiumAvaya2022$
#db1.datasource.url= jdbc:sqlserver://localhost;databaseName=appointment_remainder
#db1.datasource.username=sa
#db1.datasource.password=admin
db1.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
db1.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#db1.datasource.url= jdbc:mysql://localhost:3306/appointment_remainderauthenticationScheme=NTLM;
#db1.datasource.username=root
#db1.datasource.password=root@123
#db1.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#db1.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
db1.jpa.show-sql=true
hibernate.format_sql = true
db1.jpa.hibernate.ddl-auto=create,update

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.file.name=logs/reminder.log


#fileUpload
#call.apiurl=http://10.230.13.136/api/calltocustomer.php
call.apiurl.autocalls=http://192.168.45.71/apis/autocalls.php
#call.apiurl.autocalls=http://10.225.142.191/apis/autocalls.php
app.isFTP=true
app.fileDirectory=C:\\Users\\s-ars\\Pictures\\campaign_Copy1.csv
#failure.filediectory=C:\\Users\\Lenovo\\Pictures\\Screenshots\\Failure_
failure.filediectory=C:\\Reminder\\Failure_

#####
asterisk.manager.host=192.168.45.71
asterisk.manager.port=5038
asterisk.manager.username=amiuser
asterisk.manager.password=572b73c31395ea2e97e9742df8791535

# Dial plan config
predue.dialplan=autodial
postdue.dialplan=post-due
autodialcamp=C_02
productID=PersonalFinance

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true



cont.errorcodes=1,2,3,4,5,6,7,8,9,10,11,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,49,50,51,52,53,54,55,56,57,58,63,65,66,67,68,69,70,79,81,82,83,84,85,86,87,88,89,90,91,92,93,95,96,97,98,99,100,101,102,103,111,127,128

SOURCE_DIRECTORY=C://Program Files//Apache Software Foundation//Tomcat 9.0//logs
DESTINATION_DIRECTORY=D://Cognicx - WorkSpace//ThreadCheck//destination